AUTH_URL = 'https://accounts.spotify.com/authorize'
TOKEN_URL = 'https://accounts.spotify.com/api/token'
ME_URL = 'https://api.spotify.com/v1/me'
HISTORY_URL = 'https://api.spotify.com/v1/me/player/recently-played'
PLAYLIST_CREATE_URL = 'https://api.spotify.com/v1/users/{user_id}/playlists'
PLAYLIST_MODIFY_URL = 'https://api.spotify.com/v1/playlists/{playlist_id}'
PLAYLIST_ADD_TRACKS_URL = 'https://api.spotify.com/v1/playlists/{playlist_id}/tracks'
